#!/usr/bin/env python3

"""Alta3 Research | JOrtiz27

"name": "Joseph",
            "skill level": "fantastic".
            "spirit animal": "Goose".
            "super power": "Jet Propulsion".

joseph, a <fantastic> <Goose> of a programmer, possesses a <Jet Propulsion> factor for cascading as a superhero!

